In [1]:
import lightgbm as lgb
import os
import math
import pandas as pd
import numpy as np
import random
import gc
from datetime import datetime
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  OneHotEncoder

np.random.seed(2019)
random.seed(2019)
pd.set_option('display.max_rows', 6)
pd.set_option('display.max_columns', 10)
pd.set_option('display.width', 280)
pd.set_option('display.max_colwidth', 150)
data_path = '/data/workspace/kimi/tencent_ads/2020/dataset'
preprocess_path = 'preprocess'

In [2]:
user_base_statics_df= pd.read_pickle(f'{preprocess_path}/train_user_base_statics.pkl')
user_base_statics_df.columns = ['_'.join(i) for i in user_base_statics_df.columns.values]
label_df = pd.read_csv(f'{data_path}/train_preliminary/user.csv')
user_base_statics_df = user_base_statics_df.merge(label_df,on='user_id')
user_base_statics_df['click_times_sum_log'] = user_base_statics_df['click_times_sum'].apply(lambda x :math.log(x))
user_base_statics_df['click_times_count_log'] = user_base_statics_df['click_times_count'].apply(lambda x :math.log(x))
user_base_statics_df['age'] = user_base_statics_df['age'] -1
user_base_statics_df = user_base_statics_df.astype(float)
print(user_base_statics_df)

         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_nunique  age  gender  click_times_sum_log  click_times_count_log
0            1.0             14.0               13.0           12.0                 6.0  ...               9.0  3.0     1.0             2.639057               2.564949
1            2.0             46.0               45.0           42.0                20.0  ...              15.0  9.0     1.0             3.828641               3.806662
2            3.0             30.0               30.0           30.0                17.0  ...               8.0  6.0     2.0             3.401197               3.401197
...          ...              ...                ...            ...                 ...  ...               ...  ...     ...                  ...                    ...
899997  899998.0             15.0               14.0           14.0                 5.0  ...               5.0  3.0     2.0             2.708050               2.639057
899998  899999.0             22.0               22.0           18.0                 5.0  ...              14.0  2.0     1.0             3.091042               3.091042
899999  900000.0             12.0               12.0           12.0                 2.0  ...              10.0  2.0     2.0             2.484907               2.484907

[900000 rows x 12 columns]

In [3]:
train_df = user_base_statics_df[user_base_statics_df.user_id <= 720000]
valid_df = user_base_statics_df[user_base_statics_df.user_id > 720000]
valid_df = valid_df[valid_df.user_id < 2000000]
print(valid_df)

         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_nunique  age  gender  click_times_sum_log  click_times_count_log
720000  720001.0             32.0               28.0           26.0                11.0  ...              11.0  2.0     2.0             3.465736               3.332205
720001  720002.0             29.0               29.0           26.0                 2.0  ...              19.0  1.0     2.0             3.367296               3.367296
720002  720003.0             21.0               20.0           17.0                 8.0  ...              10.0  1.0     1.0             3.044522               2.995732
...          ...              ...                ...            ...                 ...  ...               ...  ...     ...                  ...                    ...
899997  899998.0             15.0               14.0           14.0                 5.0  ...               5.0  3.0     2.0             2.708050               2.639057
899998  899999.0             22.0               22.0           18.0                 5.0  ...              14.0  2.0     1.0             3.091042               3.091042
899999  900000.0             12.0               12.0           12.0                 2.0  ...              10.0  2.0     2.0             2.484907               2.484907

[180000 rows x 12 columns]

In [4]:
def merge_features(train_df,valid_df,train_file,valid_file,target_encode=False):
    train_features_df  = pd.read_pickle(f'{preprocess_path}/{train_file}')
    valid_features_df = pd.read_pickle(f'{preprocess_path}/{valid_file}')
    if target_encode:
        train_features_df.columns = [ '_'.join(i) for i in train_features_df.columns.values  ]
        valid_features_df.columns = ['_'.join(i) for i in valid_features_df.columns.values  ]

    train_df = train_df.merge(train_features_df,on='user_id')
    valid_df = valid_df.merge(valid_features_df,on='user_id')
    return train_df,valid_df

In [5]:
for i in ['creative_id','ad_id', 'product_id','advertiser_id','industry','product_category']:
    print(f'merge {i}...')
    train_df,valid_df = merge_features(train_df,valid_df,f'train_user_target_encoder_{i}_age.pkl',f'valid_user_target_encoder_{i}.pkl',True)
    print(train_df)
    print(valid_df)

merge creative_id...
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  creative_id_age8_kfold_mean_std  creative_id_age9_kfold_mean_min  creative_id_age9_kfold_mean_max  creative_id_age9_kfold_mean_mean  creative_id_age9_kfold_mean_std
0            1.0             14.0               13.0           12.0                 6.0  ...                         0.022296                              0.0                         0.061728                          0.016455                         0.020560
1            2.0             46.0               45.0           42.0                20.0  ...                         0.026155                              0.0                         0.500000                          0.029619                         0.074746
2            3.0             30.0               30.0           30.0                17.0  ...                         0.061345                              0.0                         0.053333                          0.006439                         0.012568
...          ...              ...                ...            ...                 ...  ...                              ...                              ...                              ...                               ...                              ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                         0.014197                              0.0                         0.045845                          0.004905                         0.009443
719998  719999.0             65.0               63.0           56.0                17.0  ...                         0.022762                              0.0                         0.250000                          0.012134                         0.033701
719999  720000.0             55.0               54.0           43.0                 6.0  ...                         0.017335                              0.0                         0.125000                          0.013262                         0.017705

[720000 rows x 52 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  creative_id_age8_kfold_mean_std  creative_id_age9_kfold_mean_min  creative_id_age9_kfold_mean_max  creative_id_age9_kfold_mean_mean  creative_id_age9_kfold_mean_std
0       720001.0             32.0               28.0           26.0                11.0  ...                         0.012118                              0.0                         0.019659                          0.005597                         0.005756
1       720002.0             29.0               29.0           26.0                 2.0  ...                         0.019975                              0.0                         0.125000                          0.008687                         0.023835
2       720003.0             21.0               20.0           17.0                 8.0  ...                         0.007798                              0.0                         0.019645                          0.001727                         0.004933
...          ...              ...                ...            ...                 ...  ...                              ...                              ...                              ...                               ...                              ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                         0.024273                              0.0                         0.041220                          0.005200                         0.011737
179998  899999.0             22.0               22.0           18.0                 5.0  ...                         0.035719                              0.0                         0.036443                          0.012363                         0.012264
179999  900000.0             12.0               12.0           12.0                 2.0  ...                         0.009143                              0.0                         0.038462                          0.004246                         0.011209

[180000 rows x 52 columns]
merge ad_id...
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  ad_id_age8_kfold_mean_std  ad_id_age9_kfold_mean_min  ad_id_age9_kfold_mean_max  ad_id_age9_kfold_mean_mean  ad_id_age9_kfold_mean_std
0            1.0             14.0               13.0           12.0                 6.0  ...                   0.022296                        0.0                   0.061728                    0.016455                   0.020560
1            2.0             46.0               45.0           42.0                20.0  ...                   0.025488                        0.0                   0.166667                    0.022005                   0.030383
2            3.0             30.0               30.0           30.0                17.0  ...                   0.061228                        0.0                   0.053333                    0.006293                   0.012390
...          ...              ...                ...            ...                 ...  ...                        ...                        ...                        ...                         ...                        ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                   0.014140                        0.0                   0.045845                    0.005020                   0.009408
719998  719999.0             65.0               63.0           56.0                17.0  ...                   0.022666                        0.0                   0.250000                    0.012123                   0.033698
719999  720000.0             55.0               54.0           43.0                 6.0  ...                   0.017304                        0.0                   0.125000                    0.013293                   0.017684

[720000 rows x 92 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  ad_id_age8_kfold_mean_std  ad_id_age9_kfold_mean_min  ad_id_age9_kfold_mean_max  ad_id_age9_kfold_mean_mean  ad_id_age9_kfold_mean_std
0       720001.0             32.0               28.0           26.0                11.0  ...                   0.012232                        0.0                   0.019659                    0.005959                   0.005681
1       720002.0             29.0               29.0           26.0                 2.0  ...                   0.034771                        0.0                   0.071429                    0.008277                   0.016171
2       720003.0             21.0               20.0           17.0                 8.0  ...                   0.007800                        0.0                   0.019645                    0.001725                   0.004933
...          ...              ...                ...            ...                 ...  ...                        ...                        ...                        ...                         ...                        ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                   0.024277                        0.0                   0.041220                    0.005199                   0.011737
179998  899999.0             22.0               22.0           18.0                 5.0  ...                   0.035719                        0.0                   0.036443                    0.012363                   0.012264
179999  900000.0             12.0               12.0           12.0                 2.0  ...                   0.009143                        0.0                   0.038462                    0.004246                   0.011209

[180000 rows x 92 columns]
merge product_id...
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  product_id_age8_kfold_mean_std  product_id_age9_kfold_mean_min  product_id_age9_kfold_mean_max  product_id_age9_kfold_mean_mean  product_id_age9_kfold_mean_std
0            1.0             14.0               13.0           12.0                 6.0  ...                        0.009306                        0.006364                        0.038736                         0.017065                        0.009112
1            2.0             46.0               45.0           42.0                20.0  ...                        0.015271                        0.005709                        0.111501                         0.023710                        0.019866
2            3.0             30.0               30.0           30.0                17.0  ...                        0.033949                        0.000000                        0.048828                         0.013551                        0.009751
...          ...              ...                ...            ...                 ...  ...                             ...                             ...                             ...                              ...                             ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                        0.009600                        0.000000                        0.024571                         0.008454                        0.006518
719998  719999.0             65.0               63.0           56.0                17.0  ...                        0.007805                        0.000000                        0.044303                         0.015102                        0.008188
719999  720000.0             55.0               54.0           43.0                 6.0  ...                        0.003226                        0.004739                        0.013493                         0.012735                        0.002174

[720000 rows x 132 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  product_id_age8_kfold_mean_std  product_id_age9_kfold_mean_min  product_id_age9_kfold_mean_max  product_id_age9_kfold_mean_mean  product_id_age9_kfold_mean_std
0       720001.0             32.0               28.0           26.0                11.0  ...                        0.010206                        0.006414                        0.040327                         0.018360                        0.010005
1       720002.0             29.0               29.0           26.0                 2.0  ...                        0.003452                        0.004212                        0.013481                         0.012842                        0.002391
2       720003.0             21.0               20.0           17.0                 8.0  ...                        0.006783                        0.000000                        0.018912                         0.010436                        0.005384
...          ...              ...                ...            ...                 ...  ...                             ...                             ...                             ...                              ...                             ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                        0.009035                        0.000000                        0.036829                         0.014503                        0.008096
179998  899999.0             22.0               22.0           18.0                 5.0  ...                        0.008332                        0.000000                        0.032789                         0.013964                        0.006131
179999  900000.0             12.0               12.0           12.0                 2.0  ...                        0.001040                        0.009473                        0.013481                         0.013147                        0.001157

[180000 rows x 132 columns]
merge advertiser_id...
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  advertiser_id_age8_kfold_mean_std  advertiser_id_age9_kfold_mean_min  advertiser_id_age9_kfold_mean_max  advertiser_id_age9_kfold_mean_mean  advertiser_id_age9_kfold_mean_std
0            1.0             14.0               13.0           12.0                 6.0  ...                           0.015910                           0.001097                           0.045790                            0.014564                           0.013377
1            2.0             46.0               45.0           42.0                20.0  ...                           0.020615                           0.000000                           0.111888                            0.025346                           0.023220
2            3.0             30.0               30.0           30.0                17.0  ...                           0.053055                           0.000000                           0.071429                            0.010871                           0.014993
...          ...              ...                ...            ...                 ...  ...                                ...                                ...                                ...                                 ...                                ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                           0.010458                           0.000000                           0.022388                            0.005387                           0.006508
719998  719999.0             65.0               63.0           56.0                17.0  ...                           0.011684                           0.000000                           0.169811                            0.016586                           0.024760
719999  720000.0             55.0               54.0           43.0                 6.0  ...                           0.008094                           0.000000                           0.030282                            0.011181                           0.006618

[720000 rows x 172 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  advertiser_id_age8_kfold_mean_std  advertiser_id_age9_kfold_mean_min  advertiser_id_age9_kfold_mean_max  advertiser_id_age9_kfold_mean_mean  advertiser_id_age9_kfold_mean_std
0       720001.0             32.0               28.0           26.0                11.0  ...                           0.017341                           0.001008                           0.098430                            0.013824                           0.018127
1       720002.0             29.0               29.0           26.0                 2.0  ...                           0.019616                           0.000000                           0.094224                            0.018020                           0.026696
2       720003.0             21.0               20.0           17.0                 8.0  ...                           0.007960                           0.000000                           0.015143                            0.006955                           0.005508
...          ...              ...                ...            ...                 ...  ...                                ...                                ...                                ...                                 ...                                ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                           0.013528                           0.000316                           0.042239                            0.014270                           0.011402
179998  899999.0             22.0               22.0           18.0                 5.0  ...                           0.011420                           0.000000                           0.023907                            0.012671                           0.007602
179999  900000.0             12.0               12.0           12.0                 2.0  ...                           0.011500                           0.000000                           0.028533                            0.008128                           0.008001

[180000 rows x 172 columns]
merge industry...
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_age8_kfold_mean_std  industry_age9_kfold_mean_min  industry_age9_kfold_mean_max  industry_age9_kfold_mean_mean  industry_age9_kfold_mean_std
0            1.0             14.0               13.0           12.0                 6.0  ...                      0.020540                      0.003626                      0.061455                       0.030320                      0.020189
1            2.0             46.0               45.0           42.0                20.0  ...                      0.011560                      0.007255                      0.071941                       0.020204                      0.012641
2            3.0             30.0               30.0           30.0                17.0  ...                      0.009268                      0.000946                      0.033865                       0.015958                      0.011770
...          ...              ...                ...            ...                 ...  ...                           ...                           ...                           ...                            ...                           ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                      0.012545                      0.000596                      0.045375                       0.008753                      0.008957
719998  719999.0             65.0               63.0           56.0                17.0  ...                      0.012776                      0.000945                      0.093551                       0.017797                      0.016583
719999  720000.0             55.0               54.0           43.0                 6.0  ...                      0.006657                      0.001390                      0.025315                       0.012785                      0.005728

[720000 rows x 212 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_age8_kfold_mean_std  industry_age9_kfold_mean_min  industry_age9_kfold_mean_max  industry_age9_kfold_mean_mean  industry_age9_kfold_mean_std
0       720001.0             32.0               28.0           26.0                11.0  ...                      0.010567                      0.002027                      0.045244                       0.018141                      0.008528
1       720002.0             29.0               29.0           26.0                 2.0  ...                      0.013174                      0.003629                      0.051030                       0.018064                      0.014107
2       720003.0             21.0               20.0           17.0                 8.0  ...                      0.007489                      0.000619                      0.033752                       0.010229                      0.007899
...          ...              ...                ...            ...                 ...  ...                           ...                           ...                           ...                            ...                           ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                      0.006878                      0.003629                      0.033752                       0.018190                      0.009288

In [6]:
def merge_w2v_features(train_df,valid_df,train_file,valid_file,f=None,target_encode=False):
    train_features_df  = pd.read_pickle(f'{preprocess_path}/{train_file}').drop([f'{f}_top0_{i}'  for i in range(64)],axis=1)
    print(train_features_df)
    valid_features_df = pd.read_pickle(f'{preprocess_path}/{valid_file}').drop([f'{f}_top0_{i}'  for i in range(64)],axis=1)
    if target_encode:
        train_features_df.columns = [ '_'.join(i) for i in train_features_df.columns.values  ]
        valid_features_df.columns = ['_'.join(i) for i in valid_features_df.columns.values  ]

    train_df = train_df.merge(train_features_df,on='user_id')
    valid_df = valid_df.merge(valid_features_df,on='user_id')
    return train_df,valid_df

In [7]:
for i in ['creative_id','ad_id', 'product_id','advertiser_id','industry']:
    print(f'merge {i}...' )
    #creative_id_top1_s64_clk.pkl
    train_df,valid_df = merge_w2v_features(train_df,valid_df,f'{i}_top1_s64_clk.pkl',f'{i}_top1_s64_clk.pkl',i,False)
    print(train_df)
    print(valid_df)

merge creative_id...
         user_id  creative_id_0  creative_id_1  creative_id_2  creative_id_3  ...  creative_id_top0_64  creative_id_mean  creative_id_std  creative_id_min  creative_id_max
0         2267.0      -1.437453      -0.779419       0.307058       0.399161  ...                    2          1.060976         0.239286                1                2
1       512898.0      -1.954691       0.417370      -0.402261      -0.314112  ...                    2          1.035088         0.184002                1                2
2       524600.0      -1.731089       1.084934      -0.111126       0.813327  ...                    2          1.029412         0.168958                1                2
...          ...            ...            ...            ...            ...  ...                  ...               ...              ...              ...              ...
899997  868400.0      -0.882293       1.556970       0.277414       1.389624  ...                    1          1.000000         0.000000                1                1
899998  742408.0      -1.639378       1.728660      -0.042359       1.802398  ...                    1          1.000000         0.000000                1                1
899999  362414.0      -1.430271       1.584868       0.109887       1.073999  ...                    1          1.000000         0.000000                1                1

[900000 rows x 70 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  creative_id_top0_64  creative_id_mean  creative_id_std  creative_id_min  creative_id_max
0            1.0             14.0               13.0           12.0                 6.0  ...                    2          1.083333         0.276385                1                2
1            2.0             46.0               45.0           42.0                20.0  ...                    2          1.071429         0.257539                1                2
2            3.0             30.0               30.0           30.0                17.0  ...                    1          1.000000         0.000000                1                1
...          ...              ...                ...            ...                 ...  ...                  ...               ...              ...              ...              ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                    1          1.000000         0.000000                1                1
719998  719999.0             65.0               63.0           56.0                17.0  ...                    4          1.125000         0.502227                1                4
719999  720000.0             55.0               54.0           43.0                 6.0  ...                    4          1.255814         0.718300                1                4

[720000 rows x 321 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  creative_id_top0_64  creative_id_mean  creative_id_std  creative_id_min  creative_id_max
0       720001.0             32.0               28.0           26.0                11.0  ...                    2          1.076923         0.266469                1                2
1       720002.0             29.0               29.0           26.0                 2.0  ...                    2          1.115385         0.319486                1                2
2       720003.0             21.0               20.0           17.0                 8.0  ...                    2          1.176471         0.381220                1                2
...          ...              ...                ...            ...                 ...  ...                  ...               ...              ...              ...              ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                    1          1.000000         0.000000                1                1
179998  899999.0             22.0               22.0           18.0                 5.0  ...                    4          1.222222         0.711458                1                4
179999  900000.0             12.0               12.0           12.0                 2.0  ...                    1          1.000000         0.000000                1                1

[180000 rows x 321 columns]
merge ad_id...
         user_id   ad_id_0   ad_id_1   ad_id_2   ad_id_3  ...  ad_id_top0_64  ad_id_mean  ad_id_std  ad_id_min  ad_id_max
0         2267.0 -0.217710 -0.967473 -0.794626 -0.415211  ...              2    1.060976   0.239286          1          2
1       512898.0  0.065644  0.005007  0.873996 -0.039156  ...              2    1.035088   0.184002          1          2
2       524600.0 -0.257614  0.378199  0.753522 -0.144750  ...              2    1.029412   0.168958          1          2
...          ...       ...       ...       ...       ...  ...            ...         ...        ...        ...        ...
899997  868400.0 -0.069290  2.169147 -0.681741 -0.385349  ...              1    1.000000   0.000000          1          1
899998  742408.0  0.089439  2.561998  0.063899 -0.594180  ...              1    1.000000   0.000000          1          1
899999  362414.0 -0.389936  1.787207 -0.541054 -0.541645  ...              1    1.000000   0.000000          1          1

[900000 rows x 70 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  ad_id_top0_64  ad_id_mean  ad_id_std  ad_id_min  ad_id_max
0            1.0             14.0               13.0           12.0                 6.0  ...              2    1.083333   0.276385          1          2
1            2.0             46.0               45.0           42.0                20.0  ...              2    1.071429   0.257539          1          2
2            3.0             30.0               30.0           30.0                17.0  ...              1    1.000000   0.000000          1          1
...          ...              ...                ...            ...                 ...  ...            ...         ...        ...        ...        ...
719997  719998.0             41.0               38.0           38.0                21.0  ...              1    1.000000   0.000000          1          1
719998  719999.0             65.0               63.0           56.0                17.0  ...              4    1.125000   0.502227          1          4
719999  720000.0             55.0               54.0           43.0                 6.0  ...              4    1.255814   0.718300          1          4

[720000 rows x 390 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  ad_id_top0_64  ad_id_mean  ad_id_std  ad_id_min  ad_id_max
0       720001.0             32.0               28.0           26.0                11.0  ...              2    1.076923   0.266469          1          2
1       720002.0             29.0               29.0           26.0                 2.0  ...              2    1.115385   0.319486          1          2
2       720003.0             21.0               20.0           17.0                 8.0  ...              2    1.176471   0.381220          1          2
...          ...              ...                ...            ...                 ...  ...            ...         ...        ...        ...        ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...              1    1.000000   0.000000          1          1
179998  899999.0             22.0               22.0           18.0                 5.0  ...              4    1.222222   0.711458          1          4
179999  900000.0             12.0               12.0           12.0                 2.0  ...              1    1.000000   0.000000          1          1

[180000 rows x 390 columns]
merge product_id...
         user_id  product_id_0  product_id_1  product_id_2  product_id_3  ...  product_id_top0_64  product_id_mean  product_id_std  product_id_min  product_id_max
0         2267.0     -0.521120     -1.919315      0.054075     -0.875846  ...                  41         4.142857        8.614969               1              41
1       512898.0     -0.365554     -2.498673      0.242244     -0.775207  ...                  28         3.277778        6.135557               1              28
2       524600.0     -0.842411     -1.436109      0.253416     -0.911230  ...                  20         1.891892        3.143279               1              20
...          ...           ...           ...           ...           ...  ...                 ...              ...             ...             ...             ...
899997  868400.0     -1.806571      0.114923     -0.444171     -1.596558  ...                   4         1.421053        0.815365               1               4
899998  742408.0     -0.674661     -0.213571     -0.119772     -0.934163  ...                   2         1.153846        0.360801               1               2
899999  362414.0     -2.573886      0.526042      0.017991     -1.895775  ...                   4         1.444444        0.955814               1               4

[900000 rows x 70 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  product_id_top0_64  product_id_mean  product_id_std  product_id_min  product_id_max
0            1.0             14.0               13.0           12.0                 6.0  ...                   7         2.166667        2.192158               1               7
1            2.0             46.0               45.0           42.0                20.0  ...                  14         2.250000        3.014548               1              14
2            3.0             30.0               30.0           30.0                17.0  ...                  10         1.764706        2.101244               1              10
...          ...              ...                ...            ...                 ...  ...                 ...              ...             ...             ...             ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                  16         1.809524        3.186565               1              16
719998  719999.0             65.0               63.0           56.0                17.0  ...                  30         3.705882        6.832145               1              30
719999  720000.0             55.0               54.0           43.0                 6.0  ...                  48         9.000000       17.445152               1              48

[720000 rows x 459 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  product_id_top0_64  product_id_mean  product_id_std  product_id_min  product_id_max
0       720001.0             32.0               28.0           26.0                11.0  ...                   6         2.545455        1.671343               1               6
1       720002.0             29.0               29.0           26.0                 2.0  ...                  27        14.500000       12.500000               2              27
2       720003.0             21.0               20.0           17.0                 8.0  ...                  12         2.500000        3.605551               1              12
...          ...              ...                ...            ...                 ...  ...                 ...              ...             ...             ...             ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                  10         2.800000        3.600000               1              10
179998  899999.0             22.0               22.0           18.0                 5.0  ...                  15         4.400000        5.425864               1              15
179999  900000.0             12.0               12.0           12.0                 2.0  ...                  11         6.000000        5.000000               1              11

[180000 rows x 459 columns]
merge advertiser_id...
         user_id  advertiser_id_0  advertiser_id_1  advertiser_id_2  advertiser_id_3  ...  advertiser_id_top0_64  advertiser_id_mean  advertiser_id_std  advertiser_id_min  advertiser_id_max
0         2267.0         1.976404        -0.313027         0.043494        -0.293499  ...                      7            1.526316           1.044707                  1                  7
1       512898.0         1.292620         1.063640        -0.507924         1.716206  ...                      3            1.204082           0.494029                  1                  3
2       524600.0         0.970978        -0.197010         1.602841        -0.864482  ...                      5            1.346154           0.874524                  1                  5
...          ...              ...              ...              ...              ...  ...                    ...                 ...                ...                ...                ...
899997  868400.0         1.285333        -0.042895         2.364430        -0.819540  ...                      4            1.350000           0.726292                  1                  4
899998  742408.0         0.870571        -0.534037         1.594872        -0.450551  ...                      2            1.071429           0.257539                  1                  2
899999  362414.0         1.119362        -0.583289         1.528105        -1.091587  ...                      4            1.444444           0.955814                  1                  4

[900000 rows x 70 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  advertiser_id_top0_64  advertiser_id_mean  advertiser_id_std  advertiser_id_min  advertiser_id_max
0            1.0             14.0               13.0           12.0                 6.0  ...                      2            1.083333           0.276385                  1                  2
1            2.0             46.0               45.0           42.0                20.0  ...                      4            1.250000           0.595119                  1                  4
2            3.0             30.0               30.0           30.0                17.0  ...                      3            1.071429           0.371154                  1                  3
...          ...              ...                ...            ...                 ...  ...                    ...                 ...                ...                ...                ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                      3            1.085714           0.368117                  1                  3
719998  719999.0             65.0               63.0           56.0                17.0  ...                      9            1.800000           1.736992                  1                  9
719999  720000.0             55.0               54.0           43.0                 6.0  ...                     19            2.076923           3.529252                  1                 19

[720000 rows x 528 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  advertiser_id_top0_64  advertiser_id_mean  advertiser_id_std  advertiser_id_min  advertiser_id_max
0       720001.0             32.0               28.0           26.0                11.0  ...                      4            1.400000           0.800000                  1                  4
1       720002.0             29.0               29.0           26.0                 2.0  ...                      5            1.611111           1.007687                  1                  5
2       720003.0             21.0               20.0           17.0                 8.0  ...                      6            1.818182           1.585054                  1                  6
...          ...              ...                ...            ...                 ...  ...                    ...                 ...                ...                ...                ...
179997  899998.0             15.0               14.0           14.0                 5.0  ...                      5            1.555556           1.257079                  1                  5
179998  899999.0             22.0               22.0           18.0                 5.0  ...                      4            1.375000           0.780625                  1                  4
179999  900000.0             12.0               12.0           12.0                 2.0  ...                      3            1.200000           0.600000                  1                  3

[180000 rows x 528 columns]
merge industry...
         user_id  industry_0  industry_1  industry_2  industry_3  ...  industry_top0_64  industry_mean  industry_std  industry_min  industry_max
0         2267.0    0.728106   -0.391725    0.056840    0.041362  ...                18       3.222222      4.424957             1            18
1       512898.0    0.717908   -0.791076   -0.306210    0.918613  ...                19       2.950000      4.924175             1            19
2       524600.0   -0.149226   -0.772887   -0.247011    0.183716  ...                18       2.800000      3.720215             1            18
...          ...         ...         ...         ...         ...  ...               ...            ...           ...           ...           ...
899997  868400.0   -0.344819   -0.086058    0.648531   -0.200103  ...                27      27.000000      0.000000            27            27
899998  742408.0   -0.344819   -0.086058    0.648531   -0.200103  ...                15      15.000000      0.000000            15            15
899999  362414.0   -0.344819   -0.086058    0.648531   -0.200103  ...                13      13.000000      0.000000            13            13

[900000 rows x 70 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_top0_64  industry_mean  industry_std  industry_min  industry_max
0            1.0             14.0               13.0           12.0                 6.0  ...                 3       1.444444      0.684935             1             3
1            2.0             46.0               45.0           42.0                20.0  ...                 9       3.000000      2.422120             1             9
2            3.0             30.0               30.0           30.0                17.0  ...                 8       3.750000      2.633913             1             8
...          ...              ...                ...            ...                 ...  ...               ...            ...           ...           ...           ...
719997  719998.0             41.0               38.0           38.0                21.0  ...                 9       1.809524      1.815779             1             9
719998  719999.0             65.0               63.0           56.0                17.0  ...                12       2.863636      2.865079             1            12
719999  720000.0             55.0               54.0           43.0                 6.0  ...                15       2.700000      3.272614             1            15

[720000 rows x 597 columns]
         user_id  click_times_sum  click_times_count  ad_id_nunique  product_id_nunique  ...  industry_top0_64  industry_mean  industry_std  industry_min  industry_max
0       720001.0             32.0               28.0           26.0                11.0  ...                 6       2.545455      2.016461             1             6
1       720002.0             29.0               29.0           26.0                 2.0  ...                 4       1.526316      0.880695             1             4

In [8]:
# train_x = train_df.drop(['age','user_id','gender','advertiser_id_seq','industry_seq','product_id_seq'], axis=1)
# train_y = train_df['age'].astype(int)

# valid_x = valid_df.drop(['age','user_id','gender','advertiser_id_seq','industry_seq','product_id_seq'], axis=1)
# valid_y = valid_df['age'].astype(int)

drop_list = ['age','user_id','gender','click_times_sum','click_times_count']
train_x = train_df.drop(drop_list, axis=1)
train_y = train_df['age'].astype(int)

valid_x = valid_df.drop(drop_list, axis=1)
valid_y = valid_df['age'].astype(int)
#print(x)
#print(y)
print(train_x)
print(train_y)

print(valid_x)
print(valid_y)

#train_x,valid_x,train_y,valid_y =  train_test_split(x,y,test_size=0.20, random_state=42)
#print(train_x.shape)
train_data = lgb.Dataset(train_x.values, label=train_y, feature_name=list(train_x.columns),free_raw_data=False)
valid_data = lgb.Dataset(valid_x.values, label=valid_y, feature_name=list(train_x.columns),free_raw_data=False,reference=train_data)

        ad_id_nunique  product_id_nunique  product_category_nunique  advertiser_id_nunique  industry_nunique  ...  industry_top0_64  industry_mean  industry_std  industry_min  industry_max
0                12.0                 6.0                       3.0                   12.0               9.0  ...                 3       1.444444      0.684935             1             3
1                42.0                20.0                       3.0                   36.0              15.0  ...                 9       3.000000      2.422120             1             9
2                30.0                17.0                       6.0                   28.0               8.0  ...                 8       3.750000      2.633913             1             8
...               ...                 ...                       ...                    ...               ...  ...               ...            ...           ...           ...           ...
719997           38.0                21.0                       5.0                   35.0              21.0  ...                 9       1.809524      1.815779             1             9
719998           56.0                17.0                       4.0                   35.0              22.0  ...                12       2.863636      2.865079             1            12
719999           43.0                 6.0                       4.0                   26.0              20.0  ...                15       2.700000      3.272614             1            15

[720000 rows x 592 columns]
0         3
1         9
2         6
         ..
719997    3
719998    3
719999    4
Name: age, Length: 720000, dtype: int64
        ad_id_nunique  product_id_nunique  product_category_nunique  advertiser_id_nunique  industry_nunique  ...  industry_top0_64  industry_mean  industry_std  industry_min  industry_max
0                26.0                11.0                       2.0                   20.0              11.0  ...                 6       2.545455      2.016461             1             6
1                26.0                 2.0                       5.0                   18.0              19.0  ...                 4       1.526316      0.880695             1             4
2                17.0                 8.0                       3.0                   11.0              10.0  ...                 4       2.000000      1.341641             1             4
...               ...                 ...                       ...                    ...               ...  ...               ...            ...           ...           ...           ...
179997           14.0                 5.0                       4.0                    9.0               5.0  ...                 8       2.800000      2.712932             1             8
179998           18.0                 5.0                       7.0                   16.0              14.0  ...                 4       1.571429      1.049781             1             4
179999           12.0                 2.0                       2.0                   10.0              10.0  ...                 2       1.200000      0.400000             1             2

[180000 rows x 592 columns]
0         2
1         1
2         1
         ..
179997    3
179998    2
179999    2
Name: age, Length: 180000, dtype: int64

In [15]:
params = {
    'boosting_type': 'gbdt',
    'objective': 'softmax',
    'num_class':10,
    'metric': 'multi_error',
    'num_leaves': 64 + 1,
    'learning_rate': 0.1,
    'feature_fraction': 0.7,
    'bagging_fraction': 0.7,
    'bagging_freq': 5,
    'lambda_l2':0.03,
    'verbose': 1
}
print('Starting training...')
# train

gbm = lgb.Booster(model_file='model/age_target.model')
#gbm.save_model('model/age_target.model')
print('Feature importances:', list(gbm.feature_importance()))

Starting training...
Feature importances: [369, 439, 163, 576, 566, 401, 380, 42, 493, 725, 413, 134, 506, 1239, 565, 165, 539, 1001, 451, 115, 428, 1067, 461, 104, 371, 835, 376, 145, 452, 941, 469, 80, 418, 924, 407, 37, 406, 787, 436, 23, 324, 661, 401, 34, 361, 611, 383, 41, 423, 696, 440, 159, 499, 1521, 621, 228, 532, 1177, 491, 186, 446, 1054, 462, 110, 358, 870, 395, 144, 455, 987, 484, 117, 438, 1147, 415, 55, 362, 951, 393, 30, 317, 702, 441, 32, 332, 580, 337, 346, 337, 337, 305, 440, 459, 396, 304, 362, 463, 312, 249, 338, 402, 309, 277, 362, 373, 402, 299, 316, 448, 380, 279, 423, 402, 303, 267, 375, 328, 229, 271, 247, 285, 218, 252, 216, 382, 257, 282, 790, 499, 743, 386, 1684, 944, 1092, 757, 1138, 883, 873, 522, 792, 1035, 693, 481, 764, 930, 606, 415, 932, 772, 676, 450, 1002, 855, 598, 361, 965, 730, 509, 374, 698, 502, 518, 343, 477, 570, 544, 336, 610, 293, 431, 423, 304, 426, 321, 365, 255, 590, 287, 340, 486, 445, 363, 446, 469, 359, 386, 355, 367, 300, 342, 352, 536, 308, 253, 359, 502, 336, 271, 289, 401, 342, 281, 325, 436, 422, 369, 318, 193, 56, 232, 391, 117, 131, 328, 223, 71, 154, 312, 265, 95, 268, 305, 272, 93, 125, 411, 251, 74, 179, 355, 314, 126, 105, 320, 257, 150, 98, 227, 199, 107, 129, 234, 201, 116, 73, 273, 212, 405, 533, 479, 409, 431, 522, 854, 522, 483, 400, 596, 640, 480, 725, 603, 422, 541, 433, 377, 412, 474, 395, 434, 612, 372, 452, 404, 407, 398, 631, 452, 627, 374, 384, 543, 433, 547, 427, 387, 398, 410, 544, 514, 562, 675, 439, 686, 369, 618, 407, 1004, 406, 511, 396, 440, 438, 482, 453, 599, 692, 441, 497, 529, 472, 36, 207, 183, 0, 14, 321, 1122, 950, 673, 350, 591, 560, 511, 485, 543, 441, 579, 573, 450, 443, 648, 416, 497, 592, 408, 371, 382, 521, 374, 587, 417, 410, 486, 473, 538, 485, 1146, 510, 380, 543, 531, 354, 408, 336, 662, 408, 479, 599, 603, 431, 433, 441, 368, 338, 453, 418, 476, 675, 509, 678, 369, 474, 447, 396, 587, 444, 394, 428, 493, 32, 162, 144, 0, 8, 340, 203, 345, 301, 243, 278, 305, 233, 237, 326, 256, 271, 285, 312, 352, 333, 323, 319, 207, 347, 348, 283, 307, 302, 319, 215, 310, 387, 182, 207, 242, 253, 336, 346, 338, 282, 289, 339, 243, 194, 279, 283, 378, 301, 228, 365, 385, 288, 308, 322, 360, 293, 374, 302, 292, 209, 277, 232, 255, 355, 445, 285, 342, 270, 298, 289, 340, 27, 87, 359, 503, 502, 380, 394, 403, 388, 576, 423, 564, 724, 375, 413, 439, 347, 555, 440, 534, 430, 468, 463, 385, 708, 487, 452, 386, 436, 402, 318, 516, 431, 689, 387, 611, 442, 539, 385, 421, 455, 483, 450, 456, 484, 653, 391, 437, 456, 407, 401, 410, 579, 334, 425, 368, 337, 555, 460, 510, 364, 342, 438, 489, 459, 346, 126, 384, 380, 2, 36, 390, 315, 271, 388, 313, 386, 391, 344, 329, 309, 327, 359, 395, 387, 362, 371, 362, 359, 568, 381, 369, 355, 479, 382, 323, 331, 316, 370, 417, 341, 304, 490, 374, 341, 313, 391, 462, 329, 383, 384, 303, 592, 324, 347, 381, 461, 312, 353, 370, 340, 334, 358, 432, 362, 363, 302, 348, 390, 335, 308, 361, 342, 378, 335, 199, 416, 404, 21, 65]

In [12]:
before_one_hot =  train_y.values.reshape([-1,1])
print(before_one_hot)
enc = OneHotEncoder()
enc.fit(before_one_hot)

one_hoted_y  = enc.transform(before_one_hot).toarray()
print(one_hoted_y.shape)

[[3]
 [9]
 [6]
 ...
 [3]
 [3]
 [4]]
(720000, 10)

/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

In [14]:
del train_df
gc.collect()

y_pred = gbm.predict(train_x.astype(float))
y_pred_percent = y_pred.copy()
for i in range(len(y_pred)):
        max_value=max(y_pred[i])
        for j in range(len(y_pred[i])):
            if max_value==y_pred[i][j]:
                y_pred[i][j]=1
            else:
                y_pred[i][j]=0
                
print(precision_score(one_hoted_y, y_pred,average='micro'))

ret = []
for user_id,age,age_percent,label_age in zip(range(1000000),y_pred,y_pred_percent,train_y):
    ret.append([int(user_id) + 1,int(age.tolist().index(1) ),age_percent,label_age])
ret_df = pd.DataFrame(ret,columns=['user_id','predicted_age','age_percent','label_age'])
print(ret_df)
ret_df.to_pickle('output/lgb_train_output.pkl')

0.20020416666666666
        user_id  predicted_age                                                                                                                                            age_percent  label_age
0             1              2  [0.03580419457322223, 0.1898360514870551, 0.29164262786260153, 0.22700110675902607, 0.06148453396238852, 0.06269398690908999, 0.08561426040271033,...          3
1             2              2  [0.1401433705682285, 0.19316240655524627, 0.23475777201241146, 0.15779094290523438, 0.08661455342297181, 0.04144567574685301, 0.11511808701112597,...          9
2             3              1  [0.08179875928343638, 0.2798110024675992, 0.21560536296149746, 0.1939984375222692, 0.0729170868976046, 0.07304765763862908, 0.047401501563739096, ...          6
...         ...            ...                                                                                                                                                    ...        ...
719997   719998              2  [0.08952754957931881, 0.20633591321347755, 0.2368157919617805, 0.19116358466345565, 0.09467535944166168, 0.05383776730122781, 0.08910878141741412,...          3
719998   719999              3  [0.04713061818270811, 0.18464282193839895, 0.2696594843908572, 0.2772952314664636, 0.058763275681544644, 0.04521381258312369, 0.08866667490863567,...          3
719999   720000              2  [0.04554685872220813, 0.2323623855047357, 0.2496605578604396, 0.24503982930725673, 0.0805779506367684, 0.03639730587165404, 0.08880146497722553, 0...          4

[720000 rows x 4 columns]

In [ ]:

before_one_hot =  valid_y.values.reshape([-1,1])
print(before_one_hot)
enc = OneHotEncoder()
enc.fit(before_one_hot)

one_hoted_y  = enc.transform(before_one_hot).toarray()
print(one_hoted_y.shape)

In [ ]:
y_pred = gbm.predict(valid_x.astype(float))
y_pred_precent =  y_pred.copy()
for i in range(len(y_pred)):
        max_value=max(y_pred[i])
        for j in range(len(y_pred[i])):
            if max_value==y_pred[i][j]:
                y_pred[i][j]=1
            else:
                y_pred[i][j]=0
                
precision_score(one_hoted_y, y_pred,average='micro')

In [ ]:
ret = []
for user_id,age,age_percent,label_age in zip(range(1000000),y_pred,y_pred_precent,valid_y):
    ret.append([int(user_id + 720001),int(age.tolist().index(1)),age_percent,label_age])
ret_df = pd.DataFrame(ret,columns=['user_id','predicted_age','age_percent','label_age'])
print(ret_df)
print(ret_df['predicted_age'].value_counts())
ret_df.to_pickle('output/lgb_output.pkl')

In [ ]:
true_user_df = ret_df[ret_df.predicted_age == ret_df.label_age ]
print(true_user_df)

In [ ]:
true_user_df = true_user_df.merge(user_base_statics_df,on='user_id')
print(true_user_df)

In [ ]:
plt_values =  true_user_df['click_times_count'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
plt_values =  true_user_df['click_times_sum'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
plt_values =  true_user_df['age'].value_counts()
print(plt_values)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
valid_user_base_statics_df =  user_base_statics_df[user_base_statics_df.user_id > 720000]
print(valid_user_base_statics_df)

In [ ]:
len_10_30_df = valid_user_base_statics_df[valid_user_base_statics_df.click_times_count > 10]
len_10_30_df = len_10_30_df[len_10_30_df.click_times_count <=20]
print(valid_user_base_statics_df)
plt_values =  len_10_30_df['age'].value_counts()
print(plt_values)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:

plt_values =  valid_user_base_statics_df['age'].value_counts()
print(plt_values)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
plt_values =  valid_user_base_statics_df['click_times_count'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
plt_values =  valid_user_base_statics_df['click_times_sum'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
valid_user_base_statics_df['click_times_sum_log'] =  valid_user_base_statics_df['click_times_sum'].apply(lambda x: math.log(x))
print(valid_user_base_statics_df)
plt_values =  valid_user_base_statics_df['click_times_sum_log'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()

In [ ]:
print(valid_user_base_statics_df)

In [ ]:
false_user_df = ret_df[ret_df.predicted_age != ret_df.label_age ]
false_user_df = false_user_df.merge(user_base_statics_df,on='user_id')
print(false_user_df)

In [ ]:
plt_values =  false_user_df['click_times_count'].value_counts().sort_index()
pd.set_option('display.max_rows', 100)
print(plt_values)
pd.set_option('display.max_rows', 6)
x = [str(i) for i in plt_values.index]
y = plt_values.values
plt.scatter(x,y)
plt.show()